type Game {
  lives: Int!
  score: Int!
  round: Round!
}

type Round {
  words: [String!]!
  giphyUrl: String!
  selectedWord: String!
}

type WordSet {
  words: [String!]!
  eid: ID!
  numReports: Int!
}
